version: '3.8'

services:
  web-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped

  # Optional: Add a development mode service
  web-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./web-ui:/app/web-ui
      - /app/web-ui/node_modules
    command: pnpm dev
    profiles:
      - dev