// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IPersonalityEvolution - Interface for agent personality evolution
/// @notice Defines the personality evolution system for Dreamscape iNFTs
/// @dev Implements personality trait development based on dream analysis
interface IPersonalityEvolution {
    
    /// @notice Core personality traits structure
    /// @dev All traits range from 0-100, dominantMood is current emotional state
    struct PersonalityTraits {
        uint8 creativity;      // 0-100: Innovation, imagination, artistic thinking
        uint8 analytical;      // 0-100: Logic, problem-solving, systematic thinking  
        uint8 empathy;         // 0-100: Emotional understanding, compassion, support
        uint8 intuition;       // 0-100: Gut feelings, spiritual insights, wisdom
        uint8 resilience;      // 0-100: Stress handling, recovery, perseverance
        uint8 curiosity;       // 0-100: Learning desire, exploration, questioning
        string dominantMood;   // Current emotional state: "peaceful", "anxious", "excited", etc.
        uint256 lastDreamDate; // Timestamp of last dream processing (prevents multiple per day)
    }

    /// @notice AI-generated unique personality features based on dream patterns
    /// @dev Discovered every 5 dreams, max 10 active features per agent
    struct UniqueUserFeature {
        string name;              // AI-generated name: "Nocturnal Philosopher", "Dream Architect"
        string description;       // Detailed description of the feature
        uint8 intensity;          // 0-100: How strong this feature is
        uint256 discoveredAt;     // Timestamp when feature was discovered
        string[] relatedSymbols;  // Dream symbols that triggered this feature
        bool isActive;            // Whether feature is currently active
        uint8 evolutionStage;     // 0-5: How developed this feature is
    }
    
    /// @notice Personality impact from dream analysis
    /// @dev Defines how a dream affects personality traits
    struct PersonalityImpact {
        int8 creativityChange;     // -10 to +10 change in creativity
        int8 analyticalChange;     // -10 to +10 change in analytical thinking
        int8 empathyChange;        // -10 to +10 change in empathy
        int8 intuitionChange;      // -10 to +10 change in intuition
        int8 resilienceChange;     // -10 to +10 change in resilience
        int8 curiosityChange;      // -10 to +10 change in curiosity
        string moodShift;          // New dominant mood
        uint8 evolutionWeight;     // 1-100: How much this dream affects personality
    }

    /// @notice AI-generated unique features to be added every 5 dreams
    /// @dev Contains 0-2 new features generated by AI based on dream analysis
    struct UniqueFeatureUpdate {
        UniqueUserFeature[] newFeatures;     // New features to add (0-2)
        string[] featuresToDeactivate;       // Names of features to deactivate
        string[] featuresToEvolve;           // Names of features to evolve
    }
    
    /// @notice Conversation context type for memory management
    enum ContextType {
        DREAM_DISCUSSION,    // Discussing previous dreams
        GENERAL_CHAT,        // General conversation
        PERSONALITY_QUERY,   // Asking about personality/traits
        THERAPEUTIC,         // Therapeutic conversation
        ADVICE_SEEKING      // Seeking advice/guidance
    }
    
    /// @notice Three-tier memory system structure
    /// @dev Each layer stores a single hash pointing to encrypted storage
    struct AgentMemory {
        bytes32 memoryCoreHash;        // Yearly summaries & agent essence
        bytes32 currentDreamDailyHash; // Append-only during current month
        bytes32 currentConvDailyHash;  // Append-only during current month
        bytes32 lastDreamMonthlyHash;  // Finalised hash after consolidation
        bytes32 lastConvMonthlyHash;   // Finalised hash after consolidation
        uint256 lastConsolidation;     // timestamp when consolidateMonth() last ran
        uint8   currentMonth;          // 1-12   (initialised at mint)
        uint16  currentYear;           // 2024+  (initialised at mint)
    }
    
    // Events
    
    /// @dev Emitted when agent personality evolves from dream processing
    event PersonalityEvolved(
        uint256 indexed tokenId,
        bytes32 indexed dreamHash,
        PersonalityTraits newPersonality,
        PersonalityImpact impact
    );

    /// @dev Emitted when new unique features are discovered
    event UniqueFeatureDiscovered(
        uint256 indexed tokenId,
        string featureName,
        string description,
        uint8 intensity,
        string[] relatedSymbols
    );

    /// @dev Emitted when unique features evolve or deactivate
    event UniqueFeatureEvolved(
        uint256 indexed tokenId,
        string featureName,
        uint8 oldStage,
        uint8 newStage,
        uint8 newIntensity
    );

    /// @dev Emitted when unique feature is deactivated
    event UniqueFeatureDeactivated(
        uint256 indexed tokenId,
        string featureName,
        string reason
    );
    
    /// @dev Emitted when agent has a conversation (without personality evolution)
    event AgentConversation(
        uint256 indexed tokenId,
        bytes32 indexed conversationHash,
        ContextType contextType,
        uint256 conversationCount
    );
    
    /// @dev Emitted when agent reaches personality milestones
    event PersonalityMilestone(
        uint256 indexed tokenId,
        string milestone,
        uint8 traitValue,
        string traitName
    );
    
    /// @dev Emitted when agent's response style evolves
    event ResponseStyleEvolved(
        uint256 indexed tokenId,
        string newStyle,
        string[] dominantTraits
    );
    
    // Core Functions
    
    /// @notice Process daily dream and evolve agent personality
    /// @param tokenId Agent to evolve
    /// @param dreamHash 0G Storage hash of encrypted dream data
    /// @param impact Personality changes from dream analysis
    /// @param uniqueFeatures AI-generated unique features (every 5 dreams)
    function processDailyDream(
        uint256 tokenId,
        bytes32 dreamHash,
        PersonalityImpact calldata impact,
        UniqueFeatureUpdate calldata uniqueFeatures
    ) external;
    
    /// @notice Record conversation without personality evolution
    /// @param tokenId Agent having conversation
    /// @param conversationHash 0G Storage hash of conversation data
    /// @param contextType Type of conversation for context building
    function recordConversation(
        uint256 tokenId,
        bytes32 conversationHash,
        ContextType contextType
    ) external;
    
    /// @notice Get agent's current personality traits
    /// @param tokenId Agent to query
    /// @return traits Current personality traits
    function getPersonalityTraits(uint256 tokenId) 
        external view returns (PersonalityTraits memory traits);

    /// @notice Get agent's unique features
    /// @param tokenId Agent to query
    /// @return features Array of unique features
    function getUniqueFeatures(uint256 tokenId)
        external view returns (UniqueUserFeature[] memory features);

    /// @notice Get specific unique feature by name
    /// @param tokenId Agent to query
    /// @param featureName Name of the feature
    /// @return feature The unique feature (empty if not found)
    function getUniqueFeature(uint256 tokenId, string calldata featureName)
        external view returns (UniqueUserFeature memory feature);
    
    /// @notice Get memory access level based on intelligence
    /// @param tokenId Agent to check
    /// @return monthsAccessible Number of months accessible 
    /// @return memoryDepth Human-readable description
    function getMemoryAccess(uint256 tokenId) external view returns (
        uint256 monthsAccessible,
        string memory memoryDepth
    );

    /// @notice Check if agent can process dream today (24h cooldown)
    /// @param tokenId Agent to check
    /// @return canProcess True if agent can process a dream today
    function canProcessDreamToday(uint256 tokenId) 
        external view returns (bool canProcess);

    /// @notice Check if consolidation is needed
    /// @param tokenId Agent to check
    /// @return isNeeded True if month has changed since last consolidation
    /// @return currentMonth Current month
    /// @return currentYear Current year
    function needsConsolidation(uint256 tokenId) external view returns (
        bool isNeeded,
        uint8 currentMonth,
        uint16 currentYear
    );

    /// @notice Get consolidation reward preview
    /// @param tokenId Agent to check
    /// @return baseReward Base intelligence reward
    /// @return streakBonus Bonus from consolidation streak
    /// @return earlyBirdBonus Bonus for early consolidation
    /// @return totalReward Total intelligence reward
    function getConsolidationReward(uint256 tokenId) external view returns (
        uint256 baseReward,
        uint256 streakBonus,
        uint256 earlyBirdBonus,
        uint256 totalReward
    );

    /// @notice Get agent's hierarchical memory structure
    /// @param tokenId Agent to query
    /// @return memory Current memory structure
    function getAgentMemory(uint256 tokenId) external view returns (AgentMemory memory);
    
    // Advanced Analytics
    
    /// @notice Get personality evolution statistics
    /// @param tokenId Agent to analyze
    /// @return totalEvolutions Number of personality changes
    /// @return evolutionRate Rate of personality change
    /// @return lastEvolution Timestamp of last evolution
    function getEvolutionStats(uint256 tokenId) 
        external view returns (
            uint256 totalEvolutions,
            uint256 evolutionRate,
            uint256 lastEvolution
        );
    

    
    /// @notice Check if agent has reached specific personality milestone
    /// @param tokenId Agent to check
    /// @param milestone Milestone to check ("empathy_master", "creative_genius", etc.)
    /// @return achieved True if milestone has been achieved
    /// @return achievedAt Timestamp when milestone was achieved (0 if not achieved)
    function hasMilestone(uint256 tokenId, string calldata milestone) 
        external view returns (bool achieved, uint256 achievedAt);
    
    // Batch Operations
    

} 